name: CD

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  #   types: [closed]

jobs:
  build:
    env:
      REPOSITORY_URL: "812935980374.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-cicd"
    name: Build and Test ECR
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Initiated Build
        run: echo "Start to build image..."

      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPOSITORY_URL }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
